# Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="UltimateKeyboard"

# Maximum Bluetooth TX Power (+8 dBm for optimal wireless range & reliability)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable USB and Bluetooth
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Enable Deep Sleep after 30 minutes of inactivity
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Battery Monitoring and Reporting over BLE
CONFIG_ZMK_BATTERY_REPORTING=y

# RGB Backlighting (SK6812MINI-E 84 LEDs)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Turn on ZMK Studio support (requires defining zmk,physical-layout in devicetree)
# CONFIG_ZMK_STUDIO=y
# CONFIG_ZMK_STUDIO_LOCKING=n
